name: Testes e upload de artefato

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Compress coverage folder
        run: zip -r coverage.zip coverage

      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test-artifact
          path: coverage.zip

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Compress build folder
        run: zip -r build.zip ./

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-artifact
          path: build.zip
